/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Oaskit Orval API
 * OpenAPI spec version: 0.0.0
 */
export type UserBodySchemaRole =
  (typeof UserBodySchemaRole)[keyof typeof UserBodySchemaRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserBodySchemaRole = {
  admin: "admin",
  user: "user",
  visitor: "visitor",
} as const

/**
 * Some body that needs to be respected by orval. Foo Bar Foo!
 */
export interface UserBodySchema {
  age: number
  name: string
  role?: UserBodySchemaRole
}

export type TestArraysParams = {
  "simple_explode_integers[]"?: number[]
}

export type TestArrays200 = { [key: string]: unknown }

export type CreateUser200 = { [key: string]: unknown }
