/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Oaskit Orval API
 * OpenAPI spec version: 0.0.0
 */
import axios from "axios"
import type { AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  CreateUser200,
  TestArrays200,
  TestArraysParams,
  UserBodySchema,
} from "./oaskitOrvalAPI.schemas"

export const getOaskitOrvalAPI = () => {
  const testArrays = <TData = AxiosResponse<TestArrays200>>(
    params?: TestArraysParams,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.get(`http://localhost:5001/orval/test-arrays`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }

  const createUser = <TData = AxiosResponse<CreateUser200>>(
    userBodySchema: UserBodySchema,
    options?: AxiosRequestConfig,
  ): Promise<TData> => {
    return axios.post(
      `http://localhost:5001/orval/users`,
      userBodySchema,
      options,
    )
  }

  return { testArrays, createUser }
}
export type TestArraysResult = AxiosResponse<TestArrays200>
export type CreateUserResult = AxiosResponse<CreateUser200>
