/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Oaskit Orval API
 * OpenAPI spec version: 0.0.0
 */
import axios from "axios"
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from "axios"

import type {
  CreateUser200,
  TestArrays200,
  TestArraysParams,
  UserBodySchema,
} from "./oaskitOrvalAPI.schemas"

export const getOaskitOrvalAPI = (axiosInstance: AxiosInstance = axios) => {
  const testArrays = (
    params?: TestArraysParams,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<TestArrays200>> => {
    return axiosInstance.get(`http://localhost:5001/orval/test-arrays`, {
      ...options,
      params: { ...params, ...options?.params },
    })
  }
  const getTestArraysUrl = (params?: TestArraysParams) => {
    return axiosInstance
      .create({
        baseURL: "",
        params: null,
      })
      .getUri({
        url: `http://localhost:5001/orval/test-arrays`,
        baseURL: "",
        params,
      })
  }

  const createUser = (
    userBodySchema: UserBodySchema,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<CreateUser200>> => {
    return axiosInstance.post(
      `http://localhost:5001/orval/users`,
      userBodySchema,
      options,
    )
  }
  const getCreateUserUrl = () => {
    return axiosInstance
      .create({
        baseURL: "",
        params: null,
      })
      .getUri({
        url: `http://localhost:5001/orval/users`,
        baseURL: "",
      })
  }

  return { testArrays, createUser, getTestArraysUrl, getCreateUserUrl }
}
export type TestArraysResult = AxiosResponse<TestArrays200>
export type CreateUserResult = AxiosResponse<CreateUser200>
