# Adds an `operation_id: "<Module>.<action>"` option to every `operation`
# macro call that has none, reproducing the default operationId generated by
# OpenApiSpex (`"#{inspect(module)}.#{action}"`). Oaskit generates a different
# default (`"#{underscore(last module segment)}_#{action}_#{hash}"`, without
# the `Controller` suffix), so without this step the operationId of those
# operations change in the OpenAPI document.
#
#     elixir pin_operation_ids.exs --project path/to/app [--write] [paths...]
#
# --write  apply the changes (dry run otherwise).
# paths    files or directories relative to --project (default: lib).
#
# Works before or after rewrite_lib.exs (it only looks at
# `operation(:action, [...])` calls).

Mix.install([{:sourceror, "~> 1.7"}])
Code.require_file("common.exs", __DIR__)
alias Migration.Common, as: C

{opts, project, files} = C.parse_args!(System.argv(), [], ["lib"])
fmt_opts = C.formatter_opts!(project)

defmodule PinOperationIds do
  import Migration.Common

  def transform(src) do
    if Regex.match?(~r/^\s*operation[\s(]+:/m, src) do
      {ast, _} =
        src
        |> Sourceror.parse_string!()
        |> Macro.traverse([], &pre/2, &post/2)

      ast
    else
      :skip
    end
  end

  # The accumulator is the stack of enclosing module names.
  defp pre({:defmodule, _, [{:__aliases__, _, parts} | _]} = node, stack) do
    name =
      case stack do
        [] -> Enum.map_join(parts, ".", &to_string/1)
        [parent | _] -> parent <> "." <> Enum.map_join(parts, ".", &to_string/1)
      end

    {node, [name | stack]}
  end

  defp pre({:operation, m, [action, spec]} = node, [mod | _] = stack) when is_list(spec) do
    if Enum.any?(spec, &(kw_key(&1) == :operation_id)) do
      {node, stack}
    else
      id = "#{mod}.#{unwrap(action)}"
      info(m, "pinned operation_id #{inspect(id)}")
      pair = {key(:operation_id), {:__block__, [delimiter: "\""], [id]}}
      {{:operation, m, [action, [pair | spec]]}, stack}
    end
  end

  defp pre(node, stack), do: {node, stack}

  defp post({:defmodule, _, _} = node, [_ | stack]), do: {node, stack}
  defp post(node, stack), do: {node, stack}
end

C.run_files(files, opts, project, fmt_opts, &PinOperationIds.transform/1)
